export const cardArray = [
  {
    id: 0,
    title: "Первый товар",
    price: 170,
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    image: "/images/card-image.jpeg",
  },
  {
    id: 1,
    title: "Второй товар",
    price: 171,
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    image: "/images/card-image.jpeg",
  },
  {
    id: 2,
    title: "Третий товар",
    price: 172,
    address: "Москва, р-н Вахитовский",
    date: "10 июля 11:39",
    image: "/images/card-image.jpeg",
  },
  {
    id: 3,
    title: "Четвертый товар",
    price: 173,
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    image: "/images/card-image.jpeg",
  },
  {
    id: 4,
    title: "Пятый товар",
    price: 174,
    address: "Москва, р-н Вахитовский",
    date: "10 июля 11:39",
    image: "/images/card-image.jpeg",
  },
  {
    id: 5,
    title: "Шестой товар",
    price: 175,
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    image: "/images/card-image.jpeg",
  },
];
